# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FishSpecies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FishSpecies
  pod 'SDWebImage', :modular_headers => true

  target 'FishSpeciesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FishSpeciesUITests' do
    # Pods for testing
  end

end
